const HOST = 'http://localhost:27017'
const LIST_DIPLOMAS = HOST + '/api/public/list'
const VERIFY_DIPLOMAS = HOST + '/api/public/verify'
const ADD_DIPLOMAS = HOST + '/api/college/add'
const LOGIN = HOST + '/api/college/login'